version: '3'

services:

    nodejs-app:
        build:
          context: ./nodejs
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - 8085:8085  
        networks:
            - example-net 

    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - 80:80 
        depends_on:
            - nodejs-app
        networks:
            - example-net 

networks:
  example-net:
    external: true
